name: Package

on:
  push:
    branches: [ main ]
    tags: [ "v*" ]
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
        key: package-${{ runner.os }}

    - name: Upgrade pip, wheel, setuptools-scm
      run: python -m pip install --upgrade build pip setuptools-scm twine wheel

    - name: Build package
      run: |
        python3 -m build --no-isolation .
        twine check dist/*

    # - name: Publish to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@v1.5.0
    #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    #   with:
    #     user: __token__
    #     password: ${{ secrets.TESTPYPI_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    #
    # - name: Publish to PyPI
    #   uses: pypa/gh-action-pypi-publish@v1.5.0
    #   if: github.event_name == 'release'
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_TOKEN }}
