name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: styfle/cancel-workflow-action@0.9.1
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: Install dependencies
      run: python -m pip install --upgrade pip pytest-cov

    - name: Run pytest to generate a coverage file
      run: pytest . --cov .

    - name: Invoke the CLI to annotate the PR
      run: python -m coverage_gh
